-- ════════════════════════════════════════════════════════
-- Chennai Smart City Pollution Monitor v2.0
-- Database Schema + Sample Data
-- Run this BEFORE starting app.py
-- ════════════════════════════════════════════════════════

DROP DATABASE IF EXISTS chennai_pollution_db;
CREATE DATABASE chennai_pollution_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE chennai_pollution_db;

-- Contaminant types
CREATE TABLE ContaminantType (
    ContaminantID   INT AUTO_INCREMENT PRIMARY KEY,
    ContaminantName VARCHAR(100) NOT NULL,
    SafeLimit       DECIMAL(10,2) NOT NULL,
    Unit            VARCHAR(20) DEFAULT 'µg/m³',
    HealthImpact    TEXT
);

-- Sensor devices (Chennai stations)
CREATE TABLE SensorDevice (
    DeviceID     INT AUTO_INCREMENT PRIMARY KEY,
    LocationName VARCHAR(150) NOT NULL,
    Latitude     DECIMAL(9,6),
    Longitude    DECIMAL(9,6),
    InstalledOn  DATE DEFAULT (CURRENT_DATE)
);

-- Sensor readings
CREATE TABLE SensorLog (
    LogID         INT AUTO_INCREMENT PRIMARY KEY,
    DeviceID      INT NOT NULL,
    PollutionType VARCHAR(20) NOT NULL,
    Value         DECIMAL(10,2) NOT NULL,
    logged_time   DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (DeviceID) REFERENCES SensorDevice(DeviceID)
);

-- Risk alerts (auto-generated by app)
CREATE TABLE RiskAlert (
    AlertID      INT AUTO_INCREMENT PRIMARY KEY,
    LogID        INT NOT NULL,
    AlertLevel   ENUM('Low','Medium','High','Critical') NOT NULL,
    AlertMessage TEXT,
    created_at   DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (LogID) REFERENCES SensorLog(LogID)
);

-- ════════════════════════════════
-- SAMPLE DATA
-- ════════════════════════════════

INSERT INTO ContaminantType (ContaminantName, SafeLimit, Unit, HealthImpact) VALUES
('CO2 (Carbon Dioxide)',   400.00, 'ppm',    'Breathing issues, dizziness, reduced concentration'),
('NO2 (Nitrogen Dioxide)',  40.00, 'µg/m³',  'Respiratory irritation, lung inflammation'),
('PM2.5 (Fine Particles)',  25.00, 'µg/m³',  'Lung damage, cardiovascular disease risk'),
('SO2 (Sulfur Dioxide)',    20.00, 'µg/m³',  'Throat irritation, asthma aggravation'),
('CO (Carbon Monoxide)',    10.00, 'mg/m³',  'Oxygen reduction, carbon monoxide poisoning');

INSERT INTO SensorDevice (LocationName, Latitude, Longitude) VALUES
('T Nagar',          13.0418, 80.2341),
('Anna Nagar',       13.0850, 80.2101),
('Adyar',            13.0012, 80.2565),
('Velachery',        12.9815, 80.2180),
('Guindy',           13.0067, 80.2206),
('OMR IT Corridor',  12.9010, 80.2279),
('Central Station',  13.0827, 80.2750),
('Chennai Airport',  12.9941, 80.1709);

-- Historical sensor readings (realistic Chennai pollution levels)
INSERT INTO SensorLog (DeviceID, PollutionType, Value, logged_time) VALUES
-- T Nagar (heavy traffic, high pollution)
(1, 'NO2',   68.4, '2025-04-26 06:00:00'),
(1, 'PM2.5', 42.1, '2025-04-26 07:00:00'),
(1, 'CO2',   445.0,'2025-04-26 08:00:00'),
(1, 'NO2',   75.2, '2025-04-26 09:00:00'),
(1, 'PM2.5', 55.8, '2025-04-26 10:00:00'),

-- Anna Nagar (residential, moderate)
(2, 'CO2',   415.0,'2025-04-26 06:30:00'),
(2, 'NO2',   38.5, '2025-04-26 07:30:00'),
(2, 'PM2.5', 22.4, '2025-04-26 08:30:00'),
(2, 'SO2',   14.2, '2025-04-26 09:30:00'),

-- Adyar (coastal, moderate-high)
(3, 'PM2.5', 31.5, '2025-04-26 06:00:00'),
(3, 'NO2',   45.8, '2025-04-26 07:00:00'),
(3, 'SO2',   22.1, '2025-04-26 08:00:00'),
(3, 'CO2',   428.0,'2025-04-26 09:00:00'),

-- Velachery (IT+residential)
(4, 'CO2',   410.5,'2025-04-26 07:00:00'),
(4, 'PM2.5', 28.7, '2025-04-26 08:00:00'),
(4, 'NO2',   35.2, '2025-04-26 09:00:00'),

-- Guindy (industrial zone — high)
(5, 'SO2',   48.3, '2025-04-26 06:00:00'),
(5, 'NO2',   82.6, '2025-04-26 07:00:00'),
(5, 'CO',    18.4, '2025-04-26 08:00:00'),
(5, 'PM2.5', 61.2, '2025-04-26 09:00:00'),
(5, 'SO2',   55.1, '2025-04-26 10:00:00'),

-- OMR IT Corridor (low-moderate)
(6, 'CO2',   395.0,'2025-04-26 07:00:00'),
(6, 'PM2.5', 19.8, '2025-04-26 08:00:00'),
(6, 'NO2',   29.4, '2025-04-26 09:00:00'),

-- Central Station (heavy traffic — high)
(7, 'CO',    14.6, '2025-04-26 06:30:00'),
(7, 'NO2',   72.1, '2025-04-26 07:30:00'),
(7, 'CO2',   460.0,'2025-04-26 08:30:00'),
(7, 'PM2.5', 48.3, '2025-04-26 09:30:00'),

-- Chennai Airport (jet fuel emissions — critical)
(8, 'CO',    22.8, '2025-04-26 07:00:00'),
(8, 'NO2',   91.4, '2025-04-26 08:00:00'),
(8, 'SO2',   38.6, '2025-04-26 09:00:00'),
(8, 'CO2',   482.0,'2025-04-26 10:00:00');
